/* eslint-disable @typescript-eslint/no-explicit-any */
'use client'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ReportFilters, type ReportFilterValues } from '@/components/tally/report-filters'
import { ProductOpportunityCard } from '@/components/tally/product-opportunity-card'
import { CustomerActionQueue } from '@/components/tally/customer-action-queue'
import { TallySyncStatus } from '@/components/tally/tally-sync-status'
import { Button } from '@/components/ui/button'
const blank: ReportFilterValues = { start:'', end:'', customer:'', product:'', category:'', staff:'', language:'' }
const money = (p:number) => `₹${(p / 100).toLocaleString('en-IN')}`
export default function TallyReportsPage() { const params = useSearchParams(); const router = useRouter(); const [filters, setFilters] = useState<ReportFilterValues>(() => Object.fromEntries(Object.keys(blank).map(k => [k, params.get(k) ?? ''])) as ReportFilterValues); const [overview, setOverview] = useState<any>(null); const [products, setProducts] = useState<any>(null); const [error, setError] = useState<string|null>(null); const [loading, setLoading] = useState(true)
 const query = useMemo(() => { const q = new URLSearchParams({ type:'overview' }); Object.entries(filters).forEach(([k,v]) => { if(v) q.set(k,v) }); return q }, [filters])
 useEffect(() => { const next = new URLSearchParams(); Object.entries(filters).forEach(([k,v]) => { if(v) next.set(k,v) }); router.replace(`/reports/tally${next.size ? `?${next}` : ''}`, { scroll:false }); setLoading(true); Promise.all([fetch(`/api/tally/reports?${query}`, {cache:'no-store'}).then(r=>r.json()), fetch(`/api/tally/reports?${new URLSearchParams(query).toString().replace('type=overview','type=products')}`, {cache:'no-store'}).then(r=>r.json())]).then(([a,b]) => { if(a.error || b.error) throw new Error(a.error ?? b.error); setOverview(a.data); setProducts(b.data); setError(null) }).catch(e=>setError(e.message)).finally(()=>setLoading(false)) }, [query, router, filters])
 return <div className="space-y-6"><div><h1 className="font-heading text-2xl font-medium">Tally reports</h1><p className="mt-1 text-sm text-muted-foreground">Explore reconciled historical sales and stock snapshots. These reports never represent a live sync.</p></div><ReportFilters value={filters} onChange={setFilters} />{loading ? <div role="status" className="h-52 animate-pulse rounded-2xl bg-muted" /> : error ? <Card><CardContent className="space-y-3 pt-6"><p role="alert" className="text-sm text-destructive">{error}</p><Button variant="outline" onClick={() => setFilters({...filters})}>Try again</Button></CardContent></Card> : overview?.reconciliation_status === 'blocked' ? <Card><CardContent className="pt-6"><Badge variant="destructive">Blocked</Badge><p className="mt-2 text-sm text-muted-foreground">Reports are unavailable until this Tally snapshot is reconciled.</p></CardContent></Card> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Revenue" value={money(overview?.revenue_paise ?? 0)} /><Metric label="Invoices" value={(overview?.invoice_count ?? 0).toLocaleString()} /><Metric label="Units" value={(overview?.units ?? 0).toLocaleString()} /><Metric label="Customers" value={(overview?.active_customers ?? 0).toLocaleString()} /><Metric label="Average order" value={money(overview?.average_order_value_paise ?? 0)} /></div><section><h2 className="mb-3 font-heading text-lg">Product opportunities</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products?.rows?.length ? products.rows.slice(0,6).map((p:any) => <ProductOpportunityCard key={p.product} {...p} value={p.gross_value_paise} />) : <p className="text-sm text-muted-foreground">No product data for this period.</p>}</div></section><CustomerActionQueue /></>}{overview && <TallySyncStatus />}</div> }
function Metric({label,value}:{label:string;value:string}) { return <Card size="sm"><CardHeader><CardTitle className="text-xs text-muted-foreground">{label}</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{value}</CardContent></Card> }
