/* eslint-disable @typescript-eslint/no-explicit-any -- test doubles and Supabase row fixtures are intentionally structural. */
import { describe, expect, it } from 'vitest';
import { extractSyncPayload } from '../src/extract';
const xml = (company: string) => `<ENVELOPE><COMPANYNAME>${company}</COMPANYNAME><COMPANYGUID>abc</COMPANYGUID><LEDGER><GUID>l1</GUID><NAME>Asha</NAME><PHONE>+91 999</PHONE></LEDGER><VOUCHER><GUID>v1</GUID><DATE>20260401</DATE><PARTYLEDGERNAME>Asha</PARTYLEDGERNAME><VOUCHERTYPENAME>Sales</VOUCHERTYPENAME><ISSALES>Yes</ISSALES><ISCANCELLED>No</ISCANCELLED><ISOPTIONAL>No</ISOPTIONAL><AMOUNT>100.00</AMOUNT><INVENTORYENTRIES.LIST><STOCKITEMNAME>Silk</STOCKITEMNAME><QUANTITY>2</QUANTITY><RATE>50</RATE><AMOUNT>100</AMOUNT></INVENTORYENTRIES.LIST></VOUCHER><STOCKITEM><GUID>s1</GUID><NAME>Silk</NAME><CLOSINGVALUE>100</CLOSINGVALUE></STOCKITEM></ENVELOPE>`;
const config = (body: string) => ({ tallyUrl: 'http://localhost:9000', companyName: 'SHALIMAR FASHIONS', tallyRelease: '7.1', fetchImpl: async () => new Response(body, { headers: { 'content-type': 'text/xml' } }) });
describe('extractSyncPayload', () => {
  it('rejects unsafe company and invalid periods before requesting XML', async () => { await expect(extractSyncPayload(config(xml('SHALIMAR FASHIONS')), { start: '2026-04-31', end: '2026-04-30' })).rejects.toThrow(/Invalid/); await expect(extractSyncPayload(config(xml('SHALIMAR FASHIONS')), { start: '2026-04-01', end: '2026-04-30' })).resolves.toBeTruthy(); });
  it('does not accept a generic NAME as company identity', async () => { await expect(extractSyncPayload(config('<ENVELOPE><NAME>SHALIMAR FASHIONS</NAME></ENVELOPE>'), { start: '2026-04-01', end: '2026-04-30' })).resolves.toBeNull(); });
  it('accepts TallyPrime company records that carry the name as an attribute', async () => { const body = '<ENVELOPE><BODY><DATA><COLLECTION><COMPANY NAME="SHALIMAR FASHIONS"><GUID>abc</GUID></COMPANY></COLLECTION></DATA></BODY></ENVELOPE>'; await expect(extractSyncPayload(config(body), { start: '2026-04-01', end: '2026-04-30' })).resolves.toBeTruthy(); });
  it('reads ledger, voucher and stock identity from Tally attribute records', async () => { const body = '<ENVELOPE><COMPANY NAME="SHALIMAR FASHIONS"><GUID>abc</GUID></COMPANY><LEDGER NAME="Asha" GUID="l1" PHONE="+91 999"/><VOUCHER VOUCHERNUMBER="v1" DATE="20260401" AMOUNT="100.00" PARTYLEDGERNAME="Asha" VOUCHERTYPENAME="Sales" ISSALES="Yes" ISCancelled="No" ISOPTIONAL="No"/><STOCKITEM NAME="Silk" GUID="s1" CLOSINGVALUE="100"/></ENVELOPE>'; const result = await extractSyncPayload(config(body), { start: '2026-04-01', end: '2026-04-30' }); expect(result?.counts).toEqual({ ledgers: 1, vouchers: 1, stock_items: 1 }); });
  it('reads the report-row shape used by Tally collection reports', async () => { const requests: string[] = []; const c = { ...config(''), fetchImpl: async (_url: any, init: any) => { const request = String(init.body); requests.push(request); const row = request.includes('fld_Phone') ? '<ROW><GUID>l1</GUID><Name>Asha</Name><Phone>+91 999</Phone></ROW>' : request.includes('fld_VoucherNumber') ? '<ROW><GUID>v1</GUID><VoucherNumber>v1</VoucherNumber><Date>20260401</Date><PartyLedgerName>Asha</PartyLedgerName><VoucherTypeName>Sales</VoucherTypeName><IsSales>Yes</IsSales><IsCancelled>No</IsCancelled><IsOptional>No</IsOptional><Amount>100.00</Amount></ROW>' : '<ROW><GUID>s1</GUID><Name>Silk</Name><ClosingValue>100</ClosingValue></ROW>'; return new Response(`<ENVELOPE><COMPANY NAME="SHALIMAR FASHIONS"><GUID>abc</GUID></COMPANY><DATA>${row}</DATA></ENVELOPE>`, { headers: { 'content-type': 'text/xml' } }); } }; const result = await extractSyncPayload(c, { start: '2026-04-01', end: '2026-04-30' }); expect(result?.counts).toEqual({ ledgers: 1, vouchers: 1, stock_items: 1 }); const voucherRequest = requests.find((body) => body.includes('fld_VoucherNumber')); expect(voucherRequest).toContain('<FULLOBJECT>Yes</FULLOBJECT>'); expect(voucherRequest).toContain('$$NumValue:$Amount'); expect(voucherRequest).toContain('<FETCH>AllInventoryEntries,PartyLedgerName,VoucherTypeName,IsSales,IsCancelled,IsOptional</FETCH>'); });
  it('reads full voucher objects with decorated amounts and inventory entries', async () => { const c = { ...config(''), fetchImpl: async (_url: any, init: any) => { const request = String(init.body); const row = request.includes('fld_VoucherNumber') ? '<ROW><GUID>v1</GUID><VoucherNumber>v1</VoucherNumber><Date>20260401</Date><PartyLedgerName>Asha</PartyLedgerName><VoucherTypeName>Sales</VoucherTypeName><IsSales>Yes</IsSales><IsCancelled>No</IsCancelled><IsOptional>No</IsOptional><Amount>125.50</Amount><ALLINVENTORYENTRIES.LIST><STOCKITEMNAME>Silk</STOCKITEMNAME><BILLEDQTY>2 nos</BILLEDQTY><RATE>62.75/nos</RATE><AMOUNT>125.50</AMOUNT></ALLINVENTORYENTRIES.LIST></ROW>' : request.includes('fld_Phone') ? '<ROW><GUID>l1</GUID><Name>Asha</Name></ROW>' : '<ROW><GUID>s1</GUID><Name>Silk</Name></ROW>'; return new Response(`<ENVELOPE><COMPANY NAME="SHALIMAR FASHIONS"><GUID>abc</GUID></COMPANY><DATA>${row}</DATA></ENVELOPE>`, { headers: { 'content-type': 'text/xml' } }); } }; const result = await extractSyncPayload(c, { start: '2026-04-01', end: '2026-04-30' }); expect(result?.vouchers[0]).toMatchObject({ grossValuePaise: 12550, lines: [{ item: 'Silk', quantity: 2, ratePaise: 6275, valuePaise: 12550 }] }); });
  it('rejects rollover dates and directly exports each defined collection', async () => { const ids: string[] = []; const c = { ...config(xml('SHALIMAR FASHIONS')), fetchImpl: async (_url: any, init: any) => { const body = String(init.body); ids.push(body.match(/<ID>(.*?)<\/ID>/)![1]); return new Response(xml('SHALIMAR FASHIONS'), { headers: { 'content-type': 'text/xml' } }); } }; await expect(extractSyncPayload(c, { start: '2026-04-31', end: '2026-05-31' })).rejects.toThrow(/Invalid/); expect(ids).toEqual([]); await extractSyncPayload(c, { start: '2026-04-01', end: '2026-04-30' }); expect(ids).toEqual(['ShalimarConnectionCompany', 'ShalimarLiveReport', 'ShalimarLiveReport', 'ShalimarLiveReport']); });
  it('reads multi-month voucher windows separately and keeps the complete period', async () => { const requests: string[] = []; const c = { ...config(''), fetchImpl: async (_url: any, init: any) => { const body = String(init.body); requests.push(body); const row = body.includes('fld_VoucherNumber') ? `<ROW><GUID>v${requests.filter((x) => x.includes('fld_VoucherNumber')).length}</GUID><VoucherNumber>v1</VoucherNumber><Date>20260615</Date><VoucherTypeName>Sales</VoucherTypeName><IsSales>Yes</IsSales><IsCancelled>No</IsCancelled><IsOptional>No</IsOptional><Amount>100</Amount></ROW>` : body.includes('fld_Phone') ? '<ROW><GUID>l1</GUID><Name>Asha</Name></ROW>' : '<ROW><GUID>s1</GUID><Name>Silk</Name></ROW>'; return new Response(`<ENVELOPE><COMPANY NAME="SHALIMAR FASHIONS"><GUID>abc</GUID></COMPANY><DATA>${row}</DATA></ENVELOPE>`, { headers: { 'content-type': 'text/xml' } }); } }; const result = await extractSyncPayload(c, { start: '2026-06-01', end: '2026-10-08' }); const voucherRequests = requests.filter((body) => body.includes('fld_VoucherNumber')); expect(voucherRequests).toHaveLength(5); expect(voucherRequests[0]).toContain('<SVFROMDATE>20260601</SVFROMDATE>'); expect(voucherRequests[0]).toContain('<SVTODATE>20260630</SVTODATE>'); expect(voucherRequests[4]).toContain('<SVFROMDATE>20261001</SVFROMDATE>'); expect(voucherRequests[4]).toContain('<SVTODATE>20261008</SVTODATE>'); expect(result?.source_period_start).toBe('2026-06-01'); expect(result?.source_period_end).toBe('2026-10-08'); expect(result?.counts.vouchers).toBe(5); });
  it('returns null for a wrong company', async () => { await expect(extractSyncPayload(config(xml('OTHER')), { start: '2026-04-01', end: '2026-04-30' })).resolves.toBeNull(); });
  it('extracts records and deterministic hashes', async () => { const period = { start: '2026-04-01', end: '2026-04-30' }; const a = await extractSyncPayload(config(xml('SHALIMAR FASHIONS')), period); const b = await extractSyncPayload(config(xml('SHALIMAR FASHIONS')), period); expect(a).toEqual(b); expect(a?.counts).toEqual({ ledgers: 1, vouchers: 1, stock_items: 1 }); expect(a?.gross_value_paise).toBe(10000); expect(a?.payload_sha256).toMatch(/^[a-f0-9]{64}$/); });
});
