'use client'
import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'

type SyncStatus = { status: string; lastRun: { id: string; received_at: string; source_period_start?: string | null; source_period_end?: string | null; reconciliation_status?: string }; snapshot?: { id?: string } | null; counts: Record<string, number>; checksum?: string | null; reconciliation?: string }
export function TallySyncStatus() {
 const [data, setData] = useState<SyncStatus | null>(null); const [error, setError] = useState<string | null>(null); const [reconcileError, setReconcileError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [reconciling, setReconciling] = useState(false)
 const load = () => { setLoading(true); fetch('/api/tally/sync-status', { cache: 'no-store' }).then(async r => { if (!r.ok) throw new Error('Unable to load sync status'); return r.json() }).then((x) => setData(x.data)).catch((e) => setError(e.message)).finally(() => setLoading(false)) }
 const reconcile = async () => { if (!data?.lastRun.id) return; setReconciling(true); setReconcileError(null); try { const response = await fetch(`/api/tally/reconcile?run_id=${encodeURIComponent(data.lastRun.id)}`, { method: 'POST' }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(typeof body?.error === 'string' ? body.error : 'Unable to reconcile this Tally run'); window.location.reload() } catch (e) { setReconcileError(e instanceof Error ? e.message : 'Unable to reconcile this Tally run') } finally { setReconciling(false) } }
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(load, [])
 if (loading) return <div role="status" aria-live="polite" className="h-40 animate-pulse rounded-2xl bg-muted" />
 if (error) return <Card><CardContent className="space-y-3 pt-6"><p role="alert" className="text-sm text-destructive">{error}</p><Button variant="outline" onClick={load}>Try again</Button></CardContent></Card>
 if (!data || !data.lastRun) return <Card><CardHeader><CardTitle>Tally sync</CardTitle><CardDescription>No Tally import has been received yet.</CardDescription></CardHeader></Card>
 const stale = data.status === 'stale'; const blocked = data.status === 'blocked'; const pending = data.status === 'pending'
 return <Card><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>Tally sync status</CardTitle><CardDescription>Historical imports stay labelled as source snapshots.</CardDescription></div><Badge variant={blocked || stale ? 'destructive' : 'secondary'}>{blocked ? 'Blocked' : pending ? 'Pending' : stale ? 'Stale' : 'Reconciled'}</Badge></div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Last run" value={new Date(data.lastRun.received_at).toLocaleString()} /><Info label="Source period" value={`${data.lastRun.source_period_start ?? '—'} – ${data.lastRun.source_period_end ?? '—'}`} /><Info label="Records" value={Object.entries(data.counts ?? {}).map(([k,v]) => `${k}: ${v}`).join(', ') || '—'} /><Info label="Checksum" value={data.checksum ? `${data.checksum.slice(0, 12)}…` : 'Unavailable'} /><p className="text-xs text-muted-foreground sm:col-span-2 lg:col-span-4">Reconciliation: {data.reconciliation ?? data.lastRun.reconciliation_status ?? 'unknown'}</p>{pending && <div className="flex flex-wrap items-center gap-3 sm:col-span-2 lg:col-span-4"><Button variant="outline" onClick={reconcile} disabled={reconciling}>{reconciling ? 'Reconciling…' : 'Reconcile latest run'}</Button><span className="text-xs text-muted-foreground">This creates the report snapshot after the counts and amount match.</span></div>}{reconcileError && <p role="alert" className="text-sm text-destructive sm:col-span-2 lg:col-span-4">{reconcileError}</p>}</CardContent></Card>
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div> }
